### PR TITLE
Changes for compiling with the latest version of conan (now without removing compiler.libcxx)

### PR DESCRIPTION
**Pull request by coding3d**
Here it is :) I hope it's good.

### CODE REVIEW

**Comment by coding3d** [comment]
There seems to be a little problem. I removed the config method from the package conanfile.py and, as I have mentioned, it still worked, but I only tried the test. AFTER making this pull request however, I noticed that I forgot to remove the method from the test's conanfile.py.

In any case, I have just discovered that I get this error when the config method is not in conanfile.py, both when building the package and the test:

ERROR: Conanfile: 'settings.compiler.libcxx' value not defined

I am not sure how to proceed, so I am open to suggestions :)

**Comment by lasote** [comment]
Hi @coding3d , I'm a little lost, What settings are you using? MinGW? The setting compiler.libcxx should be defined too for mingw. You could just set the "compiler.libcxx=libstdc++" in your conan.conf file.

**Comment by coding3d** [comment]
I'm using OSX for this build and without removing the libcxx setting, the
build was crashing. I will try to set it explicitly as you've suggested.
Thanks!

**Comment by lasote** [comment]
Yeah, you need to fill the setting with one of these values, depending what lib is your compiler using (assuming you are using clang, by default it uses libc++)
libcxx: [libstdc++, libc++]

**Comment by coding3d** [comment]
Ok! I'll try that and report back. Thanks again!

**Pull request closed without merging**
